### PR TITLE
WFNEWS-375 update for missing columns in db, update Exceptions, change indicators to Boolean, update mappers, generate guids in API

### PR DESCRIPTION
**Pull request by ssylver93**

### CODE REVIEW

**Comment by dhlevi** [comment]
@ssylver93 I'm guessing you haven't been updating your branch...

Lots of conflicts. A bunch of the added stuff was previously added. Might be worth updating, reviewing conflicts and re-pushing

**Comment by dhlevi** [comment]
Overall though, boolean updates look good

**Comment by ssylver93** [comment]
> 
@dhlevi changes looks good after re-pull and local testing

**Comment by dhlevi** [comment]
@yzlucas Note that when we merge this one in, it'll break the UI, which is expecting the old string values. We'll need to look through the UI and update instances that were looking for strings/1/T or whatever and clean them up

**Pull request merged**
