### PR TITLE
WFNEWS-2218, WFNEWS-2236, clear ionic storage to prevent duplicate ROF

### PR DESCRIPTION
**Pull request by ssylver93**
Calling ionicStorageService.clear() after submission to see if it will prevent duplicate ROFs (one was recently found in PROD 9 hours hours apart).
Fixing error when calling ionicStorage as the response was not being returned as a Promise.
Keeping ROF submissionID in localStorage so it doesn't get cleared.
Some styling to centre the text/icons on smaller screens for simple ROF questions.
image
image
image
image

### CODE REVIEW

**Comment by sukhpalp** [comment]
The question mark icon is smaller than the others. Not sure if its a code sizing thing or if the asset itself needs to be corrected.

**Comment by yzlucas** [comment]
Changes looks good. Better be very carefull about styling changes withinin ROF pages as I remembere it required a lot of effort to test on various of devices to make it works.

**Review by yzlucas — APPROVED** [review]

**Comment by sukhpalp** [comment]
Is there something missing on the Next button? Is there supposed to be an icon there? Or is it supposed to be centered?

**Review by sukhpalp — APPROVED** [review]
The code changes look good. Noticed some minor visual bugs, but they can be broken out into tickets. I agree with Lucas that making changes to the container CSS to fix buttons is a bit concerning. If we are working on this code again soon, lets try to get some of these elements broken into sandboxed components.

**Comment by yzlucas** [comment]
It is missing arrow icon on Next button, and it displays fine in current dev version. 
Not sure if it is related to the 2.6vh font-size changes in bigger screern ?

**Comment by ssylver93** [comment]
@yzlucas @sukhpalp I updated the question mark icon now, not entirely sure what was happening with the arrow icon but it shows up for locally now;
image
image
image

**Pull request merged**
