### PR TITLE
adding a photo on capacitor share

### PR DESCRIPTION
**Pull request by yzlucas**
https://apps.nrs.gov.bc.ca/int/jira/browse/WFNEWS-2422
Add a generic image on share via mobile device

### CODE REVIEW

**Comment by sukhpalp** [comment]
Don't forget to include the ticket number to the title or description.

**Review by sukhpalp — CHANGES_REQUESTED** [review]
This ticket should also cover the OpenGraph meta tags, which allows apps to fetch the image when sharing the link outside of the Capacitor share.

https://www.tektutorialshub.com/angular/dynamic-meta-tags-in-angular/

**Comment by yzlucas** [comment]
> This ticket should also cover the OpenGraph meta tags, which allows apps to fetch the image when sharing the link outside of the Capacitor share.
> 
> https://www.tektutorialshub.com/angular/dynamic-meta-tags-in-angular/

I added metaTags on sharing feature, please review. Seems like Twitter uses diffrent property for tags, Facebook and other platforms uses openGraph

**Review by sukhpalp — APPROVED** [review]

**Comment by yzlucas** [comment]
update og tage and twitter tag based on Christine's comment in the ticket https://apps.nrs.gov.bc.ca/int/jira/browse/WFNEWS-2422

**Comment by yzlucas** [comment]
added `    this.router.events
    .pipe(filter(event => event instanceof NavigationEnd))
    .subscribe(() => {
      this.setDefaultMetaTags();
    });`
    
    in app.component.ts to reset the default meta tags on page changing.

**Pull request merged**
